EtfragApp.PL/Controllers/MovieController.cs
using EtfragApp.BLL.DTOs.Movie;
using EtfragApp.BLL.DTOs.Pages;
using EtfragApp.BLL.ServicesContracts;
using EtfragApp.PL.Models.Media;
using EtfragApp.PL.Models.Movie;
using EtfragApp.PL.Models.Page;
using Microsoft.AspNetCore.Mvc;

namespace EtfragApp.PL.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IActorService _actorService;
        private readonly ICategoryService _categoryService;


        public MovieController(IMovieService movieService, IActorService actorService, ICategoryService categoryService)
        {
            _movieService = movieService;
            _actorService = actorService;
            _categoryService = categoryService;
        }

        public IActionResult Index(int pageSize = 7, int pageNo = 1, bool needCount = true, string? searchValue = null)
        {
            // Store the search value in ViewData to keep it in the form
            ViewData["SearchValue"] = searchValue;

            return View(GetPage(pageSize, pageNo, needCount, searchValue));
        }

        public IActionResult Create()
        {
            // ViewBag.Actors = _actorService.GetAll();
            ViewBag.Actors = _actorService.GetData(a => new { a.ActorId, FullName = a.FirstName + " " + a.LastName });
            ViewBag.Categories = _categoryService.GetData(c => new { c.CategoryId, c.CategoryName });

            return View("Create");
        }

        [HttpPost]
        [RequestSizeLimit(300_000_000)]
        public IActionResult Create(CreateMovieVM model)
        {
            ViewBag.Actors = _actorService.GetData(a => new { a.ActorId, FullName = a.FirstName + " " + a.LastName });
            ViewBag.Categories = _categoryService.GetData(c => new { c.CategoryId, c.CategoryName });

            if (ModelState.IsValid)
            {
                CreateMovieDTO movieDTO = new CreateMovieDTO
                {
                    Title = model.Title,
                    ThumbnailImage = model.ThumbnailImage,
                    CoverImage = model.CoverImage,
                    MediaVideo = model.MediaVideo,
                    AgeRating = model.AgeRating,
                    ActorIDs = model.ActorIDs,
                    CategoriesIDs = model.CategoriesIDs,
                    CountryOfOrigin = model.CountryOfOrigin,
                    Description = model.Description,
                    DirectorName = model.DirectorName,
                    MediaType = model.MediaType,
                    Duration = model.Duration,
                    Quality = model.Quality,
                    ReleasYear = model.ReleasYear,
                };

                _movieService.AddMovie(movieDTO);

                return RedirectToAction("Index");
            }


            return View(model);
        }

        public IActionResult Update(int id)
        {
            var movie = _movieService.GetById(id);

            MovieEditVM model = new MovieEditVM()
            {
                ThumbnailImageUrl = movie.ThumbnailImageUrl,
                CoverImageUrl = movie.CoverImageUrl,
                Title = movie.Title,
                Description = movie.Description,
                ReleasYear = movie.ReleasYear,
                Duration = movie.Duration,
                Quality = movie.Quality,
                AgeRating = movie.AgeRating,
                CountryOfOrigin = movie.CountryOfOrigin,
                DirectorName = movie.DirectorName,
                VideoURl = movie.VideoURl,
            };

            ViewBag.Actors = _actorService.GetData(a => new { a.ActorId, FullName = a.FirstName + " " + a.LastName });
            ViewBag.Categories = _categoryService.GetData(c => new { c.CategoryId, c.CategoryName });

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(int id, MovieEditVM model)
        {
            var movie = _movieService.GetById(id);

            if (movie == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                EditMovieDto movieDto = new EditMovieDto
                {
                    Id = movie.Id,
                    AgeRating = model.AgeRating,
                    CoverImage = model.CoverImage,
                    Title = model.Title,
                    Description = model.Description,
                    Duration = model.Duration,
                    Quality = model.Quality,
                    MediaVideo = model.MediaVideo,
                    ReleasYear = model.ReleasYear,
                    ThumbnailImage = model.ThumbnailImage,
                    DirectorName = model.DirectorName,
                    CountryOfOrigin = model.CountryOfOrigin,
                };

                _movieService.UpdateMovie(movieDto);

                return RedirectToAction("Index");
            }

            ViewBag.Actors = _actorService.GetData(a => new { a.ActorId, FullName = a.FirstName + " " + a.LastName });
            ViewBag.Categories = _categoryService.GetData(c => new { c.CategoryId, c.CategoryName });

            return View(model);
        }

        public IActionResult Delete(int id)
        {
            var movie = _movieService.GetById(id);
            if (movie == null)
                return NotFound();

            _movieService.Delete(id);

            TempData["Message"] = "media deleted successfuly";
            return RedirectToAction("Index");
        }

        public IActionResult TogglePopularity(int id)
        {
            var movie = _movieService.GetById(id);

            if (movie != null)
                _movieService.TogglePopularity(id);

            return RedirectToAction("Index");
        }

        //[Authorize]
        public IActionResult Details(int id)
        {
            return View(_movieService.GetMovieDetails(id));
        }

        public PageDataVM<MovieTableVM> GetPage(int pageSize, int pageNo, bool needCount, string? searchValue)
        {
            List<MovieTableVM> mappedMovies = new List<MovieTableVM>();
            PageData<MovieDto> moviePageData;


            if (searchValue is null)
                moviePageData = _movieService.Getpage(pageSize, pageNo, needCount);
            else
                moviePageData = _movieService.GetPageWithSearch(pageSize, pageNo, needCount, searchValue);

            mappedMovies = moviePageData.Data.Select(mov => new MovieTableVM
            {
                Id = mov.Id,
                Title = mov.Title,
                AgeRating = mov.AgeRating,
                AddedAt = mov.AddedAt,
                IsFeatured = mov.IsFeatured,
            }).ToList();

            return new PageDataVM<MovieTableVM>
            {
                Data = mappedMovies,
                PageNumber = pageNo,
                PageSize = pageSize,
                TotalRecords = moviePageData.TotalRecords,
            };
        }

    }
}

EtfragApp.PL/Controllers/TVSeriesController.cs
using EtfragApp.BLL.DTOs.Pages;
using EtfragApp.BLL.DTOs.TVSeries;
using EtfragApp.BLL.ServicesContracts;
using EtfragApp.PL.Models.Media;
using EtfragApp.PL.Models.Page;
using EtfragApp.PL.Models.TVShow;
using Microsoft.AspNetCore.Mvc;

namespace EtfragApp.PL.Controllers
{
    public class TVSeriesController : Controller
    {
        private readonly ITVSeriesService _tVSeriesService;
        private readonly IActorService _actorService;
        private readonly ICategoryService _categoryService;

        public TVSeriesController(
            ITVSeriesService tVSeriesService,
            IActorService actorService,
            ICategoryService categoryService)
        {
            _tVSeriesService = tVSeriesService;
            _actorService = actorService;
            _categoryService = categoryService;
        }

        public IActionResult Index(int pageSize = 7, int pageNo = 1, bool needCount = true, string? searchValue = null)
        {
            ViewData["SearchValue"] = searchValue;

            return View(GetPage(pageSize, pageNo, needCount, searchValue));
        }

        public IActionResult Create()
        {
            ViewBag.Actors = _actorService.GetData(a => new { a.ActorId, FullName = a.FirstName + " " + a.LastName });
            ViewBag.Categories = _categoryService.GetData(c => new { c.CategoryId, c.CategoryName });

            return View(new CreateTVSeriesVM());
        }

        [HttpPost]
        [RequestSizeLimit(100_000_000)]
        public IActionResult Create(CreateTVSeriesVM model)
        {
            ViewBag.Actors = _actorService.GetData(a => new { a.ActorId, FullName = a.FirstName + " " + a.LastName });
            ViewBag.Categories = _categoryService.GetData(c => new { c.CategoryId, c.CategoryName });

            if (ModelState.IsValid)
            {
                var tVSeries = new CreateTVSeriesDto
                {
                    Title = model.Title,
                    Description = model.Description,
                    ReleasYear = model.ReleasYear,
                    Quality = model.Quality,
                    AgeRating = model.AgeRating,
                    CountryOfOrigin = model.CountryOfOrigin,
                    DirectorName = model.DirectorName,
                    ActorIDs = model.ActorIDs,
                    CategoriesIDs = model.CategoriesIDs,
                    ThumbnailImage = model.ThumbnailImage,
                    CoverImage = model.CoverImage,
                    Episodes = model.Episodes,
                    MediaType = model.MediaType,
                };

                _tVSeriesService.AddTVSeries(tVSeries);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var tVSeriesDto = _tVSeriesService.GetById(id);

            EditTVSeriesVM tvseries = new EditTVSeriesVM()
            {
                ThumbnailImageUrl = tVSeriesDto.ThumbnailImageUrl,
                CoverImageUrl = tVSeriesDto.CoverImageUrl,
                Title = tVSeriesDto.Title,
                Description = tVSeriesDto.Description,
                ReleasYear = tVSeriesDto.ReleasYear,
                Quality = tVSeriesDto.Quality,
                AgeRating = tVSeriesDto.AgeRating,
                CountryOfOrigin = tVSeriesDto.CountryOfOrigin,
                DirectorName = tVSeriesDto.DirectorName,
                Episodes = tVSeriesDto.Episodes,
                

            };


            //     ViewBag.Actors = _tVSeriesService.GetEntityData(a => new { a.ActorId, FullName = a.FirstName + " " + a.LastName });
            //   ViewBag.Categories = _unitOfWork.CategoryRepository.GetEntityData(c => new { c.CategoryId, c.CategoryName });

            return View(tvseries);
        }

        [HttpPost]

        public IActionResult Delete(int id)
        {
            var tvSeries = _tVSeriesService.GetById(id);
            if (tvSeries == null)
                return NotFound();

            _tVSeriesService.Delete(id);

            TempData["Message"] = "media deleted successfuly";
            return RedirectToAction("Index");
        }

        public IActionResult TogglePopularity(int id)
        {
            var movie = _tVSeriesService.GetById(id);

            if (movie != null)
                _tVSeriesService.TogglePopularity(id);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id,int episodeNum = 1)
        {
            return View(_tVSeriesService.GetTVSeriesDetails(id,episodeNum));
        }

        public PageDataVM<TVSeriesTableVM> GetPage(int pageSize, int pageNo, bool needCount, string? searchValue)
        {
            List<TVSeriesTableVM> mappedTVSeries = new List<TVSeriesTableVM>();
            PageData<TVSeriesDto> TVSeriesPageData;


            if (searchValue is null)
                TVSeriesPageData = _tVSeriesService.Getpage(pageSize, pageNo, needCount);
            else
                TVSeriesPageData = _tVSeriesService.GetPageWithSearch(pageSize, pageNo, needCount, searchValue);

            mappedTVSeries = TVSeriesPageData.Data.Select(s => new TVSeriesTableVM
            {
                Id = s.Id,
                Title = s.Title,
                Duration = s.Duration,
                AddedAt = DateTime.Now,
                AgeRating = s.AgeRating,
                CountryOfOrigin = s.CountryOfOrigin,
                IsFeatured = s.IsFeatured,
            }).ToList();

            return new PageDataVM<TVSeriesTableVM>
            {
                Data = mappedTVSeries,
                PageNumber = pageNo,
                PageSize = pageSize,
                TotalRecords = TVSeriesPageData.TotalRecords,
            };
        }
    }
}

EtfragApp.PL/Views/Shared/_AddDismissButtonsPartialView.cshtml
<div class="modal__btns">
    <button class="btn btn-primary mx-3" type="submit">Add</button>
    <button class="btn btn-danger" type="button">Dismiss</button>
</div>

EtfragApp.PL/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/magnific-popup.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/select2.min.css">
    <link rel="stylesheet" href="~/css/admin.css">
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />

    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Dmitry Volkov">
    <title>@ViewData["Title"]</title>

</head>
<body>
    <!-- sidebar -->
    <div class="sidebar">
        <!-- sidebar user -->
        <div class="sidebar__user">
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-action="LogOut" asp-controller="Account" class="">
                    <span>Sign Out</span>
                    <i class="fa-solid fa-right-from-bracket"></i>
                </a>
            }
        </div>
        <!-- end sidebar user -->
        <!-- sidebar nav -->
        <ul class="sidebar__nav">
            <li class="m-4">
                <div class="d-inline text-primary">
                    <i class="fa-solid fa-house text-primary"></i>
                    <a asp-action="index" asp-controller="Admin" class=""><span>Dashboard</span></a>
                </div>
            </li>

            <li class="m-4">
                <div class="d-inline text-white">
                    <i class="fa-solid fa-film text-white"></i>
                    <a asp-action="index" asp-controller="Movie" class="text-white"><span>Movies</span></a>
                </div>
            </li>

            <li class="m-4">
                <div class="d-inline text-primary">
                    <i class="fa-solid fa-tv text-white"></i>
                    <a asp-action="index" asp-controller="TVSeries" class="text-white"><span>TV Series</span></a>
                </div>
            </li>
            <li class="m-4">
                <div class="d-inline text-white">
                    <i class="fa-solid fa-masks-theater"></i>
                    <a asp-action="Index" asp-controller="Actors" class="text-white"> <span>Actors</span></a>
                </div>
            </li>

            <li class="m-4">
                <div class="d-inline text-white">
                    <i class="fa-solid fa-table-cells-large text-white"></i>
                    <a asp-action="Index" asp-controller="Category" class="text-white"> <span>Categories</span></a>
                </div>
            </li>
        </ul>
        <!-- end sidebar nav -->
        <!-- sidebar copyright -->
        <div class="sidebar__copyright">© Etfrag 2024.</div>
        <!-- end sidebar copyright -->
    </div>
    <!-- end sidebar -->
    @RenderBody()
    <!-- end main content -->
    <!-- JS -->
    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/smooth-scrollbar.js"></script>
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/test.js"></script>
    <script src="~/js/admin1.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

EtfragApp.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/magnific-popup.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">


    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/select2.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/admin.css">
    <link rel="stylesheet" href="~/css/login.css">
    <link rel="stylesheet" href="~/css/main.css" />

    <!-- Favicons -->
    <link rel="icon" type="image/png" href="~/images/favicon-32x32.png" sizes="32x32">
    <link rel="apple-touch-icon" href="~/images/favicon-32x32.png">

    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Dmitry Volkov">
    <title> @ViewData["Title"]</title>

</head>
<body>
    <div class="sign section--bg" data-bg="Images/bg.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="sign__content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- JS -->
    <script src="@Url.Content("~/js/jquery-3.5.1.min.js")"></script>
    <script src="@Url.Content("~/lib/bootstrap/dist/js/bootstrap.bundle.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.magnific-popup.min.js")"></script>
    <script src="@Url.Content("~/js/smooth-scrollbar.js")"></script>
    <script src="@Url.Content("~/js/select2.min.js")"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EtfragApp.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- CSS -->
    <link rel="stylesheet" href="~/css/bootstrap-reboot.min.css" />

    <link rel="stylesheet" href="~/css/bootstrap-grid.min.css" />

    <link rel="stylesheet" href="~/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/css/slider-radio.css" />
    <link rel="stylesheet" href="~/css/select2.min.css" />
    <link rel="stylesheet" href="~/css/magnific-popup.css" />
    <link rel="stylesheet" href="~/css/plyr.css" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/magnific-popup.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">



    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/select2.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/admin.css">
    <link rel="stylesheet" href="~/css/login.css">
    <link rel="stylesheet" href="~/css/main.css" />



    <!-- Favicons -->
    <link rel="icon"
          type="image/png"
          href="icon/favicon-32x32.png"
          sizes="32x32" />
    <link rel="apple-touch-icon" href="icon/favicon-32x32.png" />

    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Dmitry Volkov" />
    <title> @ViewData["Title"]</title>
</head>

<body>

    <header class="header header--hidden">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="header__content">
                        <button class="header__menu" type="button">
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>

                        <a  asp-action="Index" asp-controller="Home" class="text-white fs-3">
                            Etfrag
                        </a>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a asp-action="LogOut" asp-controller="Account" class="header__user">
                                    <span>Sign Out</span>
                                    <i class="fa-solid fa-right-from-bracket"></i>
                                </a>
                            }
                            else
                            {
                                <a asp-action="LogIn" asp-controller="Account" class="header__user">
                                    <span>Sign In</span>
                                    <i class="fa-solid fa-right-to-bracket"></i>
                                </a>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    @RenderBody()
    <!-- footer -->
    <footer class="footer">
        <div class="footer__copyright text-center text-white">
            © Etfrag, 2024.
        </div>
    </footer>
    <!-- end footer -->
    <!-- JS -->
    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/slider-radio.js"></script>
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/smooth-scrollbar.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/plyr.min.js"></script>


    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/js/admin1.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/test.js"></script> 
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>